function company() {
    this.id = 0;
    this.companyName = "有限公司";
    this.logo = "";
    this.lang = "";
    this.wap = false;
    this.designBy = "";
    this.price = 8800;
    this.program = false;
    this.info = false;
    this.uploadtest = false;
    this.testaddress = "";
    this.upload = false;
    this.webaddress = "";
    this.createDate = "";
    this.sales = "";
    // "id": 0,
    // "companyName": "",
    // "logo": "",
    // "lang": "",
    // "wap": false,
    // "designBy": "",
    // "price": 8800,
    // "program": false,
    // "info": false,
    // "uploadtest": false,
    // "testaddress": "",
    // "upload": false,
    // "webaddress": "",
    // "createDate": "",
    // "sales": ""
};
module.exports = company;